version: 2.1
# orbs:
#   node: circleci/node@1.0.1
jobs:
  "Build Electron App":
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm-wee
          command: npm install
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: prepare-env
          command: chmod +x ./.circleci/prepare_env.sh && ./.circleci/prepare_env.sh
      - run:
          name: build
          command: npm run package-all
      - store_artifacts:
          path: ./dist
workflows:
  version: 2
  build:
    jobs:
      - Build Electron App
      # - Build Electron App:
      #     filters:
      #       branches:
      #         only:
      #           - release
