version: 2.1
# orbs:
#   node: circleci/node@1.0.1
jobs:
  node:
    working_directory: ~/trpg
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}-{{ arch }}
      - run:
          name: install-npm-wee
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}-{{ arch }}
          paths:
            - node_modules

  "Build Electron App":
    # TODO: 需要重新测试一下
    working_directory: ~/trpg/electron
    docker:
      - image: circleci/node
    steps:
      - checkout:
          path: ~/trpg
      - attach_workspace:
          at: ~/trpg
      # 更新node依赖
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}-{{ arch }}
      - run:
          name: install-npm-wee
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}-{{ arch }}
          paths:
            - node_modules
      # 更新electron依赖
      - restore_cache:
          key: electron-cache-{{ checksum "package.json" }}-{{ arch }}
      - run:
          name: install-npm-wee
          command: npm install
      - save_cache:
          key: electron-cache-{{ checksum "package.json" }}-{{ arch }}
          paths:
            - ~/.cache/electron
      - run:
          name: prepare-env
          command: chmod +x ./.circleci/prepare_env.sh && ./.circleci/prepare_env.sh
      - run:
          name: build
          command: npm run package-all
      - store_artifacts:
          path: ./dist
  "Build Android App":
    working_directory: ~/trpg/android
    docker:
      - image: circleci/android:api-27-node8-alpha
    steps:
      - checkout:
          path: ~/trpg
      - attach_workspace:
          at: ~/trpg
      # 更新node依赖
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}-{{ arch }}
      - run:
          name: install-npm-wee
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}-{{ arch }}
          paths:
            - node_modules
      - run:
          name: installDebug
          command: ./gradlew app:installDebug
workflows:
  version: 2
  build:
    jobs:
      - node
      - Build Electron App:
          requires:
            - node
          filters:
            branches:
              only:
                - release
      - Build Android App:
          requires:
            - node
